name: Build and Upload ABI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Setup dependencies (e.g., installing make)
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y make
    
    # Step 3: Run the make contract command
    - name: Build contract
      run: |
        git clone https://github.com/autonity/autonity.git
        cd autonity
        make contract
    
    # Step 4: Check if ABI files exist and create a folder if it doesn't
    - name: Create ABI folder
      run: |
        mkdir -p ./abi
        cp autonity/params/generated/*.abi ./abi/
    
    # Step 5: Commit and push ABI files
    - name: Commit and Push ABI files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Upload ABI files"
        file_pattern: "./abi/*.abi"
