name: Build and Upload ABI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Clone the autonity repository
    - name: Clone Autonity Repository
      run: |
        git clone https://github.com/autonity/autonity.git
        cd autonity
    
    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y make
    
    # Step 4: Build contract
    - name: Build contract
      run: |
        cd autonity
        make contract
    
    # Step 5: Create ABI folder and copy ABI files
    - name: Create ABI folder
      run: |
        mkdir -p ./abi
        cp autonity/params/generated/*.abi ./abi/
    
    # Step 6: Commit and Push ABI files
    - name: Commit and Push ABI files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Upload ABI files"
        file_pattern: "./abi/*.abi"
