name: Build and Upload ABI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Step 2: Clone the Autonity repository
    - name: Clone Autonity Repository
      run: git clone https://github.com/autonity/autonity.git
    
    # Step 3: Checkout the specific tag
    - name: Checkout Tag v0.14.1
      run: |
        cd autonity
        git checkout tags/v0.14.1 -b v0.14.1
    
    # Step 4: Install Dependencies
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y make
    
    # Step 5: Build contracts
    - name: Build contracts
      run: |
        cd autonity
        make contracts
    
    # Step 6: Create ABI folder and copy ABI files
    - name: Create ABI folder
      run: |
        mkdir -p ./abi
        cp autonity/params/generated/*.abi ./abi/
    
    # Step 7: Commit and Push ABI files
    - name: Commit and Push ABI files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Upload ABI files"
        file_pattern: "./abi/*.abi"
